config/routes.rb
Authproviders::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, :only => [:index, :destroy]
  root :to => 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :nickname, :provider, :url, :username, :token

  def self.find_for_facebook_oauth access_token
    if user = User.where(:url => access_token.info.urls.Facebook).first
      user.token = access_token.credentials.token 
      user
    else 
      User.create!(:provider => access_token.provider, 
                   :url => access_token.info.urls.Facebook, 
                   :username => access_token.extra.raw_info.name, 
                   :nickname => access_token.extra.raw_info.username,
                   :token => access_token.credentials.token,
                   :email => access_token.extra.raw_info.email, 
                   :password => Devise.friendly_token[0,20]) 
    end
  end

  def self.find_for_vkontakte_oauth access_token
    puts "-----------------------------------------------+++++++"
    puts access_token

    if user = User.where(:url => access_token.info.urls.Vkontakte).first
      user.token = access_token.credentials.token
      user
    else 
      User.create!(:provider => access_token.provider, 
                   :url => access_token.info.urls.Vkontakte, 
                   :username => access_token.info.name,
                   :token => access_token.credentials.token,
                   :nickname => access_token.extra.raw_info.domain,
                   :email => access_token.extra.raw_info.uid.to_s + '@vk.com',
                   :password => Devise.friendly_token[0,20]) 
    end
  end

 def getfriends
   friends =[]
   if self.provider == "facebook"
     user = FbGraph::User.me(self.token)
     user.friends.each do |f| 
       friends << f.name
     end
   else 
     vk = VkontakteApi::Client.new(self.token)
     vk.friends.get(fields: [:first_name, :last_name]).each do |f|
       friends << "#{f.first_name} #{f.last_name}"  
     end
   end  
   friends
 end
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < ApplicationController
  def facebook
    @user = User.find_for_facebook_oauth request.env["omniauth.auth"]
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      flash[:notice] = "authentication error"
      redirect_to root_path
    end
  end


  def vkontakte
  	@user = User.find_for_vkontakte_oauth request.env["omniauth.auth"]
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Vkontakte"
      sign_in_and_redirect @user, :event => :authentication
    else
      flash[:notice] = "authentication error"
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users/omniauth_callbacks_controller_helper.rb
module Users::OmniauthCallbacksControllerHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Authproviders"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/favicon.ico" rel="shortcut icon")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")

  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") Authproviders
          .container.nav-collapse
            %ul.nav
              - if user_signed_in?
                %li= link_to "#{current_user.username} (#{current_user.provider})", current_user.url
                %li= link_to "Sign out", destroy_user_session_path, :method => :delete
  .container
    .content
      .row
        - if user_signed_in?
          .span3.sidebar-nav
            %ul.nav.nav-list
              %li.nav-header="#{current_user.username} friends:"
              -current_user.getfriends.each do |m|
                .li=m
        .span6
          = yield
        .span3
          - unless user_signed_in?
            .well.sidebar-nav
              %h3 Providers
              %ul.nav.nav-list
                - if !user_signed_in?
                  %li= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook)
                  %li= link_to "Sign in with Vkontakte", user_omniauth_authorize_path(:vkontakte)

      %footer
        %p
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/users/_form.html.haml
= form_for @user do |f|
  -if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :nickname
    = f.text_field :nickname
  .field
    = f.label :provider
    = f.text_field :provider
  .field
    = f.label :url
    = f.text_field :url
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
- model_class = User.new.class
/ %h1=t '.title', :default => model_class.model_name.human.pluralize
%h1 List of users
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:username)
      / %th= model_class.human_attribute_name(:nickname)
      %th= model_class.human_attribute_name(:provider)
      / %th= model_class.human_attribute_name(:token)
      / %th= model_class.human_attribute_name(:sign_in_count)
      / %th= model_class.human_attribute_name(:created_at)
      / %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.username, user.url
        / %td= user.nickname
        %td= user.provider
        / %td= user.token
        / %td= user.sign_in_count
        / %td= user.created_at
        %td
          = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete,   :class => 'btn btn-mini btn-danger'

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Username:
  = @user.username
%p
  %b Nickname:
  = @user.nickname
%p
  %b Provider:
  = @user.provider
%p
  %b Url:
  = @user.url

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path